export const AUTH_ERRORS = {
    // Login
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    MISSING_PHONE_OR_PASSWORD: 'MISSING_PHONE_OR_PASSWORD',

    // Register
    MISSING_FIELDS: 'MISSING_FIELDS',
    PASSWORDS_DO_NOT_MATCH: 'PASSWORDS_DO_NOT_MATCH',
    PHONE_ALREADY_REGISTERED: 'PHONE_ALREADY_REGISTERED',
    EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',

    // Refresh Token
    INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
    REFRESH_TOKEN_NOT_FOUND: 'REFRESH_TOKEN_NOT_FOUND',
    MISSING_REFRESH_TOKEN: 'MISSING_REFRESH_TOKEN',

    // Reset Password
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    INVALID_OR_EXPIRED_TOKEN: 'INVALID_OR_EXPIRED_TOKEN',
    MISSING_PASSWORD: 'MISSING_PASSWORD',
    MISSING_TOKEN: 'MISSING_TOKEN',

    // Generic
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;

export type AuthErrorCode = typeof AUTH_ERRORS[keyof typeof AUTH_ERRORS];
