export const BOOKING_ERRORS = {
    // Barber
    BARBER_NOT_FOUND: 'BARBER_NOT_FOUND',
    BARBER_NOT_ACTIVE: 'BARBER_NOT_ACTIVE',

    // Booking
    BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
    SLOT_NOT_AVAILABLE: 'SLOT_NOT_AVAILABLE',
    INVALID_TIME_SLOT: 'INVALID_TIME_SLOT',
    INVALID_DATE: 'INVALID_DATE',
    BOOKING_IN_PAST: 'BOOKING_IN_PAST',
    UNAUTHORIZED_ACCESS: 'UNAUTHORIZED_ACCESS',

    // Daily Earnings
    INVALID_AMOUNT: 'INVALID_AMOUNT',
} as const;

export type BookingErrorCode = typeof BOOKING_ERRORS[keyof typeof BOOKING_ERRORS];
