export const BOOKING_ERRORS = {
    // Barber
    BARBER_NOT_FOUND: 'BARBER_NOT_FOUND',
    BARBER_NOT_ACTIVE: 'BARBER_NOT_ACTIVE',

    // Booking
    SLOT_NOT_AVAILABLE: "SLOT_NOT_AVAILABLE",
    BOOKING_NOT_FOUND: "BOOKING_NOT_FOUND",
    UNAUTHORIZED_ACCESS: "UNAUTHORIZED_ACCESS",
    INVALID_TIME_SLOT: "INVALID_TIME_SLOT",
    BOOKING_IN_PAST: "BOOKING_IN_PAST",
    INVALID_STATUS: "INVALID_STATUS",
    INVALID_AMOUNT: "INVALID_AMOUNT",
    CUSTOMER_ALREADY_BOOKED: "CUSTOMER_ALREADY_BOOKED",
} as const;

export type BookingErrorCode = typeof BOOKING_ERRORS[keyof typeof BOOKING_ERRORS];
